[general]
working_directory = "D:\\workshop\\"

[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Return"
mods = "Alt"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[terminal]
shell = "zsh"
